export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS'

export const CREATE_MY_ADDRESS_SUCCESS = 'CREATE_MY_ADDRESS_SUCCESS'
export const CREATE_CUSTOMER_ADDRESS_SUCCESS = 'CREATE_CUSTOMER_ADDRESS_SUCCESS'
