export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS'

export const CREATE_CUSTOMER_ADDRESS_SUCCESS = 'CREATE_CUSTOMER_ADDRESS_SUCCESS'

export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'

export const GET_TRANSACTION_HISTORY_SUCCESS = 'GET_TRANSACTION_HISTORY_SUCCESS'

export const LOAD_CURRENT_BITCOIN_SUCCESS = 'LOAD_CURRENT_BITCOIN_SUCCESS'
